### ISSUE TITLE
Utils should not have .py in filename

### ISSUE THREAD

**Issue by libavgIssueImporter** [libavg/libavg#191]
*this ticket is transfered from former bug tracking system*

rename avg_*.py -> avg_*

Reason: The scripts are installed to bin/ directories. By convention, files there have no extension.

----
__author:__ [uzadow](https://github.com/uzadow)
__created:__ 2011/03/08 00:52:54 +0100
__assigned to:__ None
__priority:__ Normal
__project:__ libavg

**Comment by uzadow** [comment]
Fixed with 7515daa6
