### ISSUE TITLE
Clean up the libavg namespace.

### ISSUE THREAD

**Issue by libavgIssueImporter** [libavg/libavg#291]
*this ticket is transfered from former bug tracking system*

- [X] grabbable, draggable, eventList, clusteredEventList should die.
- [x] See if we can kill mathutil and trackerhelper as well.
- [x] textarea should move to the ui package.
- [x] fadeIn/Out, getNumRunningAnims() should be static members of the Anim base class.
- [x] getMemoryUsage() should be player.getMemoryUsage().
- [x] getSupportedPixelFormats() -> player.
- [x] pointInPolygon -> Point2D.isInPolygon()?

----
__author:__ [uzadow](https://github.com/uzadow)
__created:__ 2012/01/30 17:48:02 +0100
__assigned to:__ None
__priority:__ Normal
__project:__ libavg

**Comment by uzadow** [comment]
Anim namespace: 3b5c76f9c0a5e02c05c8672a7b24cdc4a6cf73f7
