### ISSUE TITLE
testBitmapManager fails sometimes

### ISSUE THREAD

**Issue by libavgIssueImporter** [libavg/libavg#365]
*this ticket is transfered from former bug tracking system*

testBitmapManager fails occasionally with a "BitmapManager didn't reply within 2000ms timeout" error. The failure occurs immediately, not after 2000 ms.

There might be an interaction with Player.setFakeFPS().

----
__author:__ [uzadow](https://github.com/uzadow)
__created:__ 2012/11/08 10:57:49 +0100
__assigned to:__ [oxullo](https://github.com/oxullo)
__priority:__ Normal
__project:__ libavg

**Comment by uzadow** [comment]
The bug still happens on the windows build server, e.g.:
https://www.libavg.de/bb/builders/i386-win-full/builds/1923/steps/shell_2/logs/stdio

**Comment by uzadow** [comment]
Seems to have been fixed by e1c3863.
