### ISSUE TITLE
./Test.py --usegles breaks widget classes

### ISSUE THREAD

**Issue by libavgIssueImporter** [libavg/libavg#415]
_this ticket is transfered from former bug tracking system_

--usegles causes Player.useGLES() to be called, which switches the default pixel format from BGR to RGB. This means all bitmaps loaded before the useGLES() call are broken.

The skin module loads its default skin during module initialization. Result: 

<pre>
RuntimeError: Assertion failed in GLTexture.cpp: 240
</pre>

Changing avgrc doesn't cause the error. Can we remove --usegles?

---

---

**author:** [uzadow](https://github.com/uzadow)
**created:** 2013/04/11 21:57:45 +0200
**assigned to:** [klemmster](https://github.com/klemmster)
**priority:** Normal
**project:** libavg

**Comment by scotty007** [comment]
OpenGLES2 unit tests can be run by building libavg with AVG_ENABLE_EGL (forces GLES2) or with `<gles>true</gles>` in `avgrc` on a GLX build with a driver supporting GLES2 (both options for Linux only).
