### ISSUE TITLE
Ending fullscreen program doesn't return to old resolution

### ISSUE THREAD

**Issue by libavgIssueImporter** [libavg/libavg#437]
*this ticket is transfered from former bug tracking system*

On OS X Mountain Lion, ending fullscreen firebirds doesn't reset the screen to the old resolution. Users are left with a messed-up desktop.

----
__author:__ [uzadow](https://github.com/uzadow)
__created:__ 2013/07/09 10:00:27 +0200
__assigned to:__ None
__priority:__ Normal
__project:__ libavg

**Comment by uzadow** [comment]
Can't reproduce anymore.
