### ISSUE TITLE
r9573 breaks fullscreen reset in "testAppRotation" on Ubuntu

### ISSUE THREAD

**Issue by libavgIssueImporter** [libavg/libavg#481]
*this ticket is transfered from former bug tracking system*

@​make check@​ fails and leaves the desktop in 640x480 resolution:
<pre>
testAppRotation (AppTest.AppTestCase) ... X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  150 (XFree86-VidModeExtension)
  Minor opcode of failed request:  10 (XF86VidModeSwitchToMode)
  Value in failed request:  0x3a00003
  Serial number of failed request:  1551
  Current serial number in output stream:  1553
FAIL: Test.py
</pre>

sys config: Ubuntu 12.04-x86_64, NVidia GTX260 / NVidia driver 304.116

----
__author:__ [scotty007](https://github.com/scotty007)
__created:__ 2014/02/20 11:05:46 +0100
__assigned to:__ None
__priority:__ Normal
__project:__ libavg

**Comment by uzadow** [comment]
@scotty007: I've just pushed a possible fix to master (b995370e3eff2f42eaaddd8e550e5bbc81919eea). Can you see if you can reproduce the bug and verify the fix? I'd like to close this.

**Comment by scotty007** [comment]
I tested the current master on different problematic systems w/o any failures. Closing this issue...

**Comment by uzadow** [comment]
Yay! :-)
