### ISSUE TITLE
WordsNode rendering broken

### ISSUE THREAD

**Issue by scotty007** [libavg/libavg#622]
The buildbot log files of all three platforms report differences for all WordsNode related tests. Looking at some result images on my machine (same test results) shows that centered and right aligned text is rendered left aligned and all lines are offset a few pixels up.

**Comment by scotty007** [comment]
example images:

baseline
![testparawords_baseline](https://cloud.githubusercontent.com/assets/1743413/6696899/dd7fb2b4-ccec-11e4-8e11-f3604df200c9.png)

result
![testparawords](https://cloud.githubusercontent.com/assets/1743413/6696900/e30ad20e-ccec-11e4-8c14-8bfb86482730.png)

**Comment by uzadow** [comment]
Ouch. I might have time over the weekend to work on this. A git bisect would help a lot :-).

**Comment by scotty007** [comment]
bisected: fbc7ad7825f9373470ee1e05aec560453136960c is the first bad commit

**Comment by uzadow** [comment]
Duh. Thanks :-).
