### ISSUE TITLE
Compiling failed on the new Raspberry Pi2

### ISSUE THREAD

**Issue by Nelson666** [libavg/libavg#623]
Hello,

I try to compile libavg on the new RPI2. I've checked out the master branch.
1.) ./bootstrap
2.) ./configure --enable-rpi --prefix=/home/pi/raspberryPi2/install_release
3.) make

ERROR:
Making all in player
make[3]: Entering directory '/home/pi/raspberryPi2/libavg_org/src/player'
  CXX    OGLSurface.lo
  CXX    Arg.lo
  CXX    AreaNode.lo
  CXX    RasterNode.lo
RasterNode.cpp: In member function 'void avg::RasterNode::blt(avg::GLContext*, const mat4&, const vec2&)':
RasterNode.cpp:453:68: error: no matching function for call to 'avg::GLTexture::activate(avg::WrapMode (&)(), int)'
RasterNode.cpp:453:68: note: candidate is:
../graphics/GLTexture.h:47:10: note: void avg::GLTexture::activate(const avg::WrapMode&, int)
../graphics/GLTexture.h:47:10: note:   no known conversion for argument 1 from 'avg::WrapMode()' to 'const avg::WrapMode&'
Makefile:705: recipe for target 'RasterNode.lo' failed
make[3]: *** [RasterNode.lo] Error 1
make[3]: Leaving directory '/home/pi/raspberryPi2/libavg_org/src/player'
Makefile:385: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/pi/raspberryPi2/libavg_org/src'
Makefile:323: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/raspberryPi2/libavg_org/src'
Makefile:389: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by uzadow** [comment]
I've checked in a possible fix - can you do a git pull, try again and report the results?
For other RPi issues, have a look at #612

**Comment by Nelson666** [comment]
Hey, that's it. The compiling works with --enable-rpi.
Thank you. 

Close

**Comment by cstranex** [comment]
@Nelson666 What version of Raspbian were you using?

**Comment by Nelson666** [comment]
uname -a
Linux raspberrypi 3.18.7-v7+ #755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015 armv7l GNU/Linux
