### ISSUE TITLE
Linux Build Server: No space left on device

### ISSUE THREAD

**Issue by uzadow** [libavg/libavg#624]
The latest Linux build failed with: 
```
EaseInOutAnim.cpp:71:1: fatal error: opening dependency file .deps/EaseInOutAnim.Tpo: Read-only file system
 }
 ^
compilation terminated.
{standard input}: Assembler messages:
{standard input}: Fatal error: can't write .libs/EaseInOutAnim.o: Read-only file system
{standard input}: Fatal error: can't close .libs/EaseInOutAnim.o: No space left on device
Cannot create temporary file in ./: Read-only file system
```
@klemmster, @oxullo: Could you have a look?

**Comment by uzadow** [comment]
https://www.libavg.de/bb/builders/x64-lnx-full/builds/1845/steps/compile/logs/stdio

**Comment by oxullo** [comment]
Hefty filesystem failure.
I have to access the console, though. Will do tomorrow!

> On Mar19, 2015, at 15:15 , Ulrich von Zadow <notifications@github.com> wrote:
> 
> The latest Linux build failed with:
> 
> EaseInOutAnim.cpp:71:1: fatal error: opening dependency file .deps/EaseInOutAnim.Tpo: Read-only file system
>  }
>  ^
> compilation terminated.
> {standard input}: Assembler messages:
> {standard input}: Fatal error: can't write .libs/EaseInOutAnim.o: Read-only file system
> {standard input}: Fatal error: can't close .libs/EaseInOutAnim.o: No space left on device
> Cannot create temporary file in ./: Read-only file system
> @klemmster <https://github.com/klemmster>, @oxullo <https://github.com/oxullo>: Could you have a look?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/libavg/libavg/issues/624>.
> 

--
OXullo Intersecans

**Comment by uzadow** [comment]
Looks fixed, closing. Thanks!

**Comment by oxullo** [comment]
Yeah, even though I'm not sure it was a drive or controller issue.. fingers crossed! I took also the chance to automate X startup.
