### ISSUE TITLE
Windows 64-bit Version

### ISSUE THREAD

**Issue by adammhaile** [libavg/libavg#638]
Is there every going to be a precompiled 64-bit installer for Windows? I would love to use this library in a project, but many of my users have 64-bit installs (most of them actually) and it seems that compiling for 64-bit is overly complicated.

**Comment by uzadow** [comment]
libavg compiles and runs fine under 64 bit windows. Only python needs to be 32 bit.
Does that solve your issue?

**Comment by adammhaile** [comment]
No :( I need to be able to run 64 bit python as well.

**Comment by adammhaile** [comment]
I thought 64 was the default install now?

**Comment by uzadow** [comment]
Hm, I understand.
A libavg build for 64 bit python under windows would be a nice thing to have, but I'm afraid you're the first one that's asked for it. So: I'd be happy to help you get a 64 bit version running :-), but I don't have the time to work on that myself.

**Comment by adammhaile** [comment]
Apparently I'm weird in using 64... What is involved? And would it be
possible to then make an installer?

**Comment by uzadow** [comment]
No, you're not weird in using 64-bit python - I think it's just that most people can easily switch to 32 bit.

Anyway, if you can build it, you can build an installer pretty easily: https://www.libavg.de/site/projects/libavg/wiki/WindowsInstaller
The main issue is finding and building the 64-bit versions of the dependencies. Basically, for every library in windependencies-1.7.0.zip, we need to find a 64-bit version. There's some hints at the bottom of the win source install page, but they're outdated.

**Comment by adammhaile** [comment]
Yeah... I'm just trying to find a good cross-platform UI toolkit for python
and want to make the install as easy as possible for users since some will
have no real experience with all this stuff. Maybe if there was a way to
package the 32-bit build from my machine as a Windows exe? (of my
application that is, with all dependencies)

**Comment by adammhaile** [comment]
Just going to install 32-bit python for now. After a bit of a survey, turns out I'm the weird one using 64 bit :P Thanks!
