### ISSUE TITLE
Forum account registration broken

### ISSUE THREAD

**Issue by uzadow** [libavg/libavg#640]
Creating a forum account on libavg.de fails with:

"""
There was an error with the recaptcha code below. Please re-enter the code and click submit.
"""
There is no recaptcha code to be seen.

@oxullo: Do you have an idea? Otherwise, I'll have a look.

**Comment by oxullo** [comment]
Fixed! A mixed-content issue with the recaptcha script being called from non-SSL source. Fixed in https://github.com/srstclair/redmine_recaptcha/commit/b027cf1969df8bc69565b5eee0804504dc995bd5 and pulled to libavg's website

**Comment by uzadow** [comment]
Thanks!
