### ISSUE TITLE
Set fill color as RGB value without HTML Hex code

### ISSUE THREAD

**Issue by adammhaile** [libavg/libavg#641]
Mostly an enhancement request... would it be possible to, instead of requiring HTML color codes, allow setting colors via the Pixel32 object instead? Better yet, from python just allow a 3 value tuple, like (128,255,64). All my color values are stored as those tuples already and I have to convert them to HTML codes first to use LibAVG. doesn't add *that* much  overhead I guess, just an extra step that seems unnecessary. Thanks!

**Comment by uzadow** [comment]
Heh :-) - we have that as a feature request already: #570
