### ISSUE TITLE
Access callFromThread in MainDiv derived class

### ISSUE THREAD

**Issue by adammhaile** [libavg/libavg#642]
Sorry... me again :P
I've been scouring the docs for a few hours now and I can't figure out how to use callFromThread() when using a MainDiv derived app, like in the vector sample. I want to draw to some vectors from data coming in over a TCP connection but I cannot figure out the proper way to call into the main UI thread and can't see a way to access any sort of underlying Player object on which I can use callFromThread(). Is that just not available in MainDiv classes? Do I need to just make my own Player object for use?

**Comment by scotty007** [comment]
That's quite easy, just call `player.callFromThread()` inside your threaded python code and provide it a method to execute in the libavg main thread:

```
from libavg import player

def foo():
    # executed in a python thread
    player.callFromThread(bar)

def bar():
    # executed in main thread
    pass
```

To pass parameters to your main thread method use a lambda operator:

```
player.callFromThread(lambda: bar(param1, param2))
```

**Comment by adammhaile** [comment]
Ok, I've done that but I'm still getting crashes all the time. The below code crashes every time after 10-15 seconds:

```python
import libavg
from libavg import app, geom, player

import time
import threading

import os, sys

from bibliopixel import *

from bibliopixel.drivers.network_receiver import ThreadedDataServer, ThreadedDataHandler


class VectorDiv(app.MainDiv):
    def onInit(self):
        self._pixels = []
        self.w = 32
        self.h = 32
        self.pixelSize = 10

        self.initGrid()

        self._hasFrame = False

        self.data = [0]*self.w*self.h*3

        address = ('localhost', 1618)
        try:
            server = ThreadedDataServer(address, ThreadedDataHandler)
            server.update = self.update
            #server.hasFrame = self.hasFrame

            t = threading.Thread(target=server.serve_forever)
            t.setDaemon(True) # don't hang on exit
            t.start()#
        except Exception as e:
            log.logger.exception(e)
            log.logger.error("Unable to open port. Another visualizer is likely running. Exiting...")
            sys.exit(2)

    def toHexColor(self, r,g,b):
        return "{0:02x}{1:02x}{2:02x}".format(r,g,b)

    def onFrame(self):
    	try:
	        data = self.data
	        for x in range(self.w):
	            for y in range(self.h):
	                i = x+(y*self.w)
	                r = data[i * 3 + 0]
	                g = data[i * 3 + 1]
	                b = data[i * 3 + 2]

	                p = self._pixels[i]
	                p.fillcolor = self.toHexColor(r,g,b)
        except Exception, e:
        	print "onFrame Error"
        	print e

    def initGrid(self):
        pw = self.pixelSize
        ph = pw
        for x in range(self.w):
            for y in range(self.h):
                n = libavg.RectNode(pos=(x*pw,y*ph), color="666666", fillopacity=1, 
                    fillcolor="000000", size=(pw,ph), parent=self)
                self._pixels.append(n)


    def __updatePixels(self, data):
    	try:
        	self.data = data
        except Exception, e:
    		print "__updatePixels error"
    		print e

    # def hasFrame(self):
    # 	return self._hasFrame

    def update(self, data):
    	try:
    	# self._hasFrame = True
    		player.callFromThread(lambda: self.__updatePixels(data))
    	except Exception, e:
    		print "update error"
    		print e

app.App().run(VectorDiv(), app_resolution='500x500')

```

Any thoughts on why? No error message or anything is output as far as I'm aware. In the console it just looks like the script returned normally, other than getting a Windows dialog stating that the python process has abruptly terminated.  The script sending data to this is just on a TCP connection and fails gracefully when the above script crashes.

**Comment by scotty007** [comment]
Hmm, I don't see anything problematic in the code you posted. If you provide your `bibliopixel` module and a TCP data provider I can run a test here.

BTW: If your data update rate is lower than the frame rate, I'd set the fillcolors in `__updatePixels()` instead of `onFrame()`. Saves you from running the nested loops in every frame...
