### ISSUE TITLE
Raspbian: Canvas misaligned with window

### ISSUE THREAD

**Issue by master-nevi** [libavg/libavg#654]
**Platform:** Raspberry Pi A+, Raspbian, Wheezy
**libavg Version:** 1.8.2 & 1.8.1 (compiled on raspberry and cross-compiled on another machine)

**Code:**
```Python
#!/usr/bin/env python
from libavg import avg, app, player

class ShapesMainDiv(app.MainDiv):
	def onInit(self):
		avg.RectNode(pos=(10,10), size=(40,40), fillopacity=1, fillcolor='0000FF', strokewidth=0, parent=self)

	def onExit(self):
		pass

	def onFrame(self):
		pass

app.App().run(ShapesMainDiv(), app_resolution='200x200')
```

**Screenshot** (had to use my phone as "scrot" screenshots didn't capture the canvas at all):
![img_3615](https://cloud.githubusercontent.com/assets/987706/7447704/a785f61c-f1ba-11e4-9157-75d92c65ca41.JPG)

**Comment by uzadow** [comment]
This is a duplicate to #652. I'll leave this one open since it has the better description.

**Comment by uzadow** [comment]
The offset is a result of the overscan settings in /boot/config.txt. If you set disable_overscan=1 in that file, the window is positioned correctly. Unfortunately, it doesn't look like it's possible to query the overscan settings in a sane way. I'll close this for now, but if there are important ramifications I'm missing, I can add an environment variable would allow setting an offset manually.

In the long run, we need to update to using libsdl 2.0.x, which has support for the Pi built-in. Right now, all of the work is done by hand in libavg, making things a bit fragile.

**Comment by master-nevi** [comment]
Thank you, your solution worked. It also got rid of that nasty black frame around the entire Desktop environment.
