### ISSUE TITLE
Font rendering broken on Ubuntu 14.04LTS

### ISSUE THREAD

**Issue by scotty007** [libavg/libavg#677]
It seems all WordsNodes are rendered with the same font family, variant and size as the last created one. Happens only on Ubuntu 14.04, works on Ubuntu 12.04 and OSX.

The breaking commit is 46633afceb2cd4cda87dd87da21a11d6ed2c3045 (Unneeded code removal.)

`avg_showfont.py 'DejaVu Serif'` example images:

broken:
![avg_showfont_01](https://cloud.githubusercontent.com/assets/1743413/8286148/4260105e-1908-11e5-8edf-4bfc8799a7fb.png)

working:
![avg_showfont_02](https://cloud.githubusercontent.com/assets/1743413/8286156/4c123b18-1908-11e5-96cf-48ed4becb132.png)

**Comment by uzadow** [comment]
Ouch, ok. Feel free to revert the commit!

**Comment by uzadow** [comment]
Thanks!
