### ISSUE TITLE
Non self-intersecting PolygonNode throws 'Non-simple Polygon Exception'

### ISSUE THREAD

**Issue by bluscr33n** [libavg/libavg#684]
In some cases a PolygonNode can throw a non-simple polygon exception - although the polygon seems not to be self-intersecting or degenerated.

Example:
```
from libavg import app, avg


class MainDiv(app.MainDiv):
    def onInit(self):
        pts = [(-5,575), (90, 500),  (444, 500), (454, 278), (464, 215), (505, 389), (515, 389), (969, 500), (1000,575)]
        avg.PolygonNode(
            pos=pts,
            parent=self
        )


app.App().run(MainDiv(), app_resolution='1400, 800')
```
This code causes a crash of the application. That is a bit strange, since the points should give a simple polygon (see attached image generated by pyplot). Also, if you remove *any* point from the list, the code works fine.

![figure_1](https://cloud.githubusercontent.com/assets/4332104/8961538/18e279bc-3616-11e5-9fe1-558d7991b8a0.png)

**Comment by payload** [comment]
The triangulation code is generating a triangle with vertices 5, 1 and 7. This triangle contains (444, 500). And in the end the algorithm runs out of vertices to triangulate. I have put your example into a test case on my branch: https://github.com/payload/libavg/commit/2c7d6fa7544d465223b3018ed204a39d188bac88
