### ISSUE TITLE
WordsNode: Wrong rendering when using multiple WordsNode

### ISSUE THREAD

**Issue by bluscr33n** [libavg/libavg#687]
I observed a pretty strange behaviour of WordsNode: When working with multiple WordsNode with different text, the rendering can get buggy. In fact, if found two cases (or levels?) of failure:

1) Wrong content
The WordsNode can display the wrong content / text. See the following example:
```python
from libavg import app, avg
import random


class MainDiv(app.MainDiv):
    def onInit(self):
        for x in range(4):
            for y in range(4):
                avg.WordsNode(
                    parent=self,
                    text='(%i, %i)' % (x, y),
                    pos=(x * 50, y * 25),
                )


app.App().run(MainDiv(), app_resolution='250, 300')
```
The result should be like this:
```
(0,0)(1,0)…(3,0)
(0,1)(1,1)…(3,1)
…
(0,3)(1,3)…(3,3)
```
But what I got is this (see column 2 and 3 at row 3 and 4):
![wordsnode_bug](https://cloud.githubusercontent.com/assets/4332104/9035577/92004736-39d9-11e5-8104-755a203600f7.png)

2) Rendering failure
When adding more Nodes with different content, rendering failures occur. I extended the example from above with a second block:
```python
from libavg import app, avg
import random


class MainDiv(app.MainDiv):
    def onInit(self):
        for x in range(4):
            for y in range(4):
                avg.WordsNode(
                    parent=self,
                    text='(%i, %i)' % (x, y),
                    pos=(x * 50, y * 25),
                )

        for x in range(4):
            for y in range(4):
                val = float(random.randrange(10000)) / 100
                avg.WordsNode(
                    parent=self,
                    text='%.2f' % val,
                    pos=(x * 50, y * 25 + 150),
                    fontsize=14
                )


app.App().run(MainDiv(), app_resolution='250, 300')
```
The result is the following:
![wordsnode_bug_2](https://cloud.githubusercontent.com/assets/4332104/9035637/1af078cc-39da-11e5-8014-cd114a2fafcc.png)

I'm working on Ubuntu 14.04 and with an up-to-date libavg version.

**Comment by bluscr33n** [comment]
The problem seems to depend on the system. On a second system, running Linux Mint 17.2, the rendering is actual fine. I will fire up a `make test` tomorrow on the first system and will update this issue.

**Comment by uzadow** [comment]
What hardware is this running on?

**Comment by bluscr33n** [comment]
* Hardware: AMD Radeon R7 250
* Driver: Proprietary (fglrx-updates)
* Test result images: The `testRawText` images as well as `testSimpleWords` images are fine. Only the `testI18NWords` images show some differences.
