### ISSUE TITLE
No cursor events and gesture recognizer on strokes

### ISSUE THREAD

**Issue by tflemisch** [libavg/libavg#688]
I encountered the problem that strokes don't react to cursor events or gesture recognizer.
It was reported in this issue before: https://github.com/libavg/libavg/issues/664

Here is an example which shows the problem:
https://gist.github.com/tflemisch/8b84fe859b8c1aa455be

**Comment by uzadow** [comment]
Implementation should be straightforward for all vector nodes except CurveNodes, where a brute-force solution would probably be too slow.
Code for calculation of the distance from a cubic spline to a point is here: https://github.com/erich666/GraphicsGems/blob/master/gems/NearestPoint.c.
