### ISSUE TITLE
Fail to build on Fedora 22 - No avcodec.h detected

### ISSUE THREAD

**Issue by Enduni** [libavg/libavg#697]
Hi,

I tried to build libavg from source, using the instructions on the official website. After carefully installing all equivalent dependencies, finally the ./configure command finished without errors. But make aborted with these lines;

    Making all in video
    make[3]: Entering directory '/home/enduni/Entwicklung/libavg-1.8.2/src/video'
      CXX      FFMpegDemuxer.lo
    In file included from FFMpegDemuxer.h:27:0,
                     from FFMpegDemuxer.cpp:22:
    WrapFFMpeg.h:43:32: fatal error: libavcodec/avcodec.h: No such file or directory
compilation terminated.

`sudo make` yielded the same results.

I know for a fact that I possess this header;

    [enduni@localhost libavg-1.8.2]$ sudo find / -iname "avcodec.h"
    find: "/run/user/1000/gvfs": Keine Berechtigung
    /usr/include/ffmpeg/libavcodec/avcodec.h
    /usr/include/ffmpeg/libavfilter/avcodec.h

Is there any way to fix this error on my part, is it something to easily fix in the source or should I just try to install libavg on my Windows partition (since I don't want to install an Ubuntu and I see your point if you say that you cannot support all Linux distributions)? Also, I don't really need the video functionality of libavg right now - is there a way to compile libavg without it and to possibly circumvent this error?

Cheers,
Enduni

**Comment by uzadow** [comment]
This is a question of making sure the build system looks in the right places for the header, and finding the header is configure's responsibility. 
What is the output of configure?
Can you attach config.log?

**Comment by Enduni** [comment]
Of course. 
* [Console Output of ./configure](http://pastebin.ca/3164919)
* [config.log](http://pastebin.ca/3164921)

**Comment by uzadow** [comment]
This does look like it's a bug in the libavg ffmpeg detection.
I've committed a possible fix on the bugfix/fedora_ffmpeg branch. Can you check that branch out, see if it runs and report back so I can commit it to master?

**Comment by Enduni** [comment]
Hey,

thanks for the quick bugfix. Your fix detects ffmpeg correctly. Building libavg now works without any errors, but there are about 30 `deprecated` warnings. I ran `make check` to make sure that everything works - and it sadly does not. I don't know if the errors are related, but it seems quite likely. I enclosed all my logs, if you want to have a look. 

* [./configure log](http://pastebin.com/ERQtQdme)
* [config.log file](http://pastebin.com/LuB4V7HF)
* [make log](http://pastebin.com/tPFKrCfc)
* [make check log](http://pastebin.com/YVMv2CYc)

Cheers,
Enduni

**Comment by uzadow** [comment]
The errors are unrelated :-). Looks like Fedora has a different (probably newer) version of Fontconfig.
I've checked in another possible fix - could you try again?

**Comment by Enduni** [comment]
It's somewhat of a success I assume, but make check still quits with a failure message. Here's the [log](http://pastebin.com/kQXvmQYw). My fontconfig version is currently 2.11.94 if that helps.

**Comment by uzadow** [comment]
Ok, we're running into lots of different configuration-related things here.
The fontconfig issue is fixed, and I assume what we're seeing now is graphics card/driver-related things.

It's probably best if I have a chance to sit at the computer that's failing. You're not in Dresden by any chance? If yes, you could stop by my room next week (not this week, we have a deadline) and I can see what I can do.

**Comment by Enduni** [comment]
I actually live in Dresden, but I think that it won't be necessary. Since you said, it could be graphics-related, I tried using optirun. And I can run `make check` without any failures using optirun / my dedicated graphics card instead of my on board chip. :) So I'll just have to run libavg programs with optirun and all should be fine.

Thank you very much for your help! 

Cheers,
Enduni

**Comment by uzadow** [comment]
Cool, I've merged and closed everything.
