### ISSUE TITLE
Cross-compilation configuration fails because of unmet package requirement (although it's installed)

### ISSUE THREAD

**Issue by PooSham** [libavg/libavg#700]
I'm cross-compiling for my RPi2 from my Ubuntu 12.04-machine following the instructions [here](https://www.libavg.de/site/projects/libavg/wiki/RaspberryPISourceInstall). When running ./rpi-configure I get (along with other unimportant stuff) this message:
> checking for GDK_PIXBUF_CFLAGS... 
> checking for GDK_PIXBUF_LIBS... -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lpcre -lc
> configure: error: Package requirements (gdk-pixbuf-2.0) were not met.
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.

> Alternatively you may set the GDK_PIXBUF_CFLAGS and GDK_PIXBUF_LIBS environment variables
> to avoid the need to call pkg-config.  See the pkg-config man page for
> more details.

Then I run the following:
> $ pkg-config --list-all | grep gdk-pixbuf
> gdk-pixbuf-xlib-2.0            GdkPixbuf Xlib - GdkPixbuf rendering for Xlib
> gdk-pixbuf-2.0                 GdkPixbuf - Image loading and scaling

So obviously I have gdk-pixbuf-2.0 installed and pkg-config recognizes it.

**Comment by uzadow** [comment]
You need to have gdk-pixbuf (and the other libs) installed on the Pi, not the build machine. They are then copied to the build machine and used for compiling.

Closing. If you have more issues of this sort, the forums (https://www.libavg.de/site/projects/libavg/boards) are the right place to look for help.

**Comment by PooSham** [comment]
Thanks.

The forum doesn't seem to work. I never got a mail after registration and can't log in.

**Comment by uzadow** [comment]
Hm - I'll have a look. Did you get the build to work?
