### ISSUE TITLE
Add mouse wheel support

### ISSUE THREAD

**Issue by uzadow** [libavg/libavg#712]
Mouse wheel events are currently ignored. Make it possible to use the mouse wheel from libavg apps. Wheel events should be sent to the node under the mouse cursor and handled like MOUSE_UP/DOWN/...-Events.

**Comment by scotty007** [comment]
Before the switch to SDL2, mouse wheel events were handled the same way as mouse button clicks, they just got different button numbers (usually 4 and 5) assigned in the mouse event. Re-implement this behaviour?

**Comment by uzadow** [comment]
Actually, I think different events are better. In the old condition, you would have to subscribe to general mouse events and then use an if to detect the wheel. The new proposal means you only get wheel events if you actually subscribe to them directly.
