### ISSUE TITLE
Back face culling behavior is different in a canvas

### ISSUE THREAD

**Issue by DevNils** [libavg/libavg#715]
Hey Folks,

recently I used a MeshNode. I made use of the back face culling. When I moved this node to a offscreen canvas, I saw all the back faces instead of the front faces.
I did some research but I could not find the problem.
My following example visualizes the problem. I have to identical mesh nodes, one is in the main tree, the other is in a canvas. One shows the front faces, the other shows the back faces.
The example runs with git commit caf74b2.

Thank you in advance

Nils

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    
    
    from libavg import app, avg, player
    from libavg.app import MainDiv as AVGMainDiv
    
    
    class MainDiv(AVGMainDiv):
        def onInit(self):
    
            canvas = player.createCanvas(
                id="canvas",
                size=(self.size.x / 2., self.size.y)
            )
    
            # --- creating example texture ---
            rect1 = avg.RectNode(
                parent=canvas.getRootNode(),
                opacity=0,
                fillopacity=1,
                fillcolor='FF0000',
                size=(self.size.x / 4., self.size.y)
            )
            rect2 = avg.RectNode(
                parent=canvas.getRootNode(),
                opacity=0,
                fillopacity=1,
                fillcolor='00FF00',
                size=(self.size.x / 4., self.size.y),
                pos=(self.size.x / 4., 0)
            )
    
            canvas.render()
            meshTexture = canvas.screenshot()
            rect1.unlink(True)
            rect2.unlink(True)
            # ---------------------------------
    
            vertexCoords = [
                (0, 0), (self.size.x / 2., 0),
                (self.size.x / 2., self.size.y), (0, self.size.y)
            ]
            texCoords = [
                (0, 0), (1, 0),
                (1, 1), (0, 1)
            ]
            triangles = [
                (1, 0, 3), (1, 2, 3)
            ]
    
            mesh1 = avg.MeshNode(
                vertexcoords=vertexCoords,
                texcoords=texCoords,
                triangles=triangles,
                parent=self,
                backfacecull=True
            )
            mesh1.setBitmap(meshTexture)
    
            mesh2 = avg.MeshNode(
                vertexcoords=vertexCoords,
                texcoords=texCoords,
                triangles=triangles,
                parent=canvas.getRootNode(),
                backfacecull=True
            )
            mesh2.setBitmap(meshTexture)
    
            avg.ImageNode(
                pos=(self.size.x / 2. , 0),
                parent=self,
                href='canvas:canvas'
            )
    
    
    if __name__ == '__main__':
        app.App().run(MainDiv())

**Comment by uzadow** [comment]
Fixed with  b6d63ac
