### ISSUE TITLE
DragRecognizer in a canvas in a rotated app behaves strange

### ISSUE THREAD

**Issue by DevNils** [libavg/libavg#716]
Hey Folks,

I found a problem in the DragRecognizer. I use it in an unusual way. My app is rotated and the recognizer listens to node which is inside a canvas.
If the app is not rotated the recognizer works like expected. If you turn the app to the left or right, the recognizer movement position has some sort of fixed offset, depending on the event nodes position.
You can see this in the following example. If you exec the app unrotated it works, if you start the app with --app-rotation=right you will see some strange offset in the movement position.

Thank you for your help or any ideas what I did wrong.

Nils

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    
    
    from libavg import app, avg, player, gesture
    from libavg.app import MainDiv as AVGMainDiv
    
    
    class MainDiv(AVGMainDiv):
        def onInit(self):
    
            canvas = player.createCanvas(
                id="canvas",
                size=self.size,
                handleevents=True
            )
    
            rect = avg.RectNode(
                parent=canvas.getRootNode(),
                size=(100, 100),
                opacity=0,
                fillopacity=1,
                fillcolor='FF0000'
            )
            rect.pos = (self.size.x / 2. - rect.size.x / 2.,
                        self.size.y / 2. - rect.size.y / 2.)
    
            label = avg.WordsNode(
                parent=self
            )
    
            def detectedHandler():
                rect.fillcolor = '00FF00'
    
            def handleMove(event):
                label.text = 'x:%s y:%s' % (event.x, event.y)
    
            def handleUp():
                rect.fillcolor = 'FF0000'
    
            self.img = avg.ImageNode(
                parent=self,
                href='canvas:canvas'
            )
    
            self.recognizer = gesture.DragRecognizer(
                eventNode=rect,
                detectedHandler=detectedHandler,
                moveHandler=handleMove,
                endHandler=handleUp,
                coordSysNode=self.img
            )
    
    
    if __name__ == '__main__':
        app.App().run(MainDiv())

**Comment by uzadow** [comment]
I had a look, and the bug definitely exists. Unfortunately, this looks complicated. 

The bug is buried in the conversion of local (node-specific) to global coordinates. If the node is inside a canvas, this conversion ends at the root node of the canvas. Since it is possible to show the canvas in several ImageNodes, it is unclear through which image node the conversion should pass.

So I'm not sure whether to just document this and say 'wontfix' or actually fix it. How important is it?

**Comment by DevNils** [comment]
Right now I have workaround for this problem. It is not that urgent.
