### ISSUE TITLE
Get Event position of DoubleTap with DoubletapRecognizer

### ISSUE THREAD

**Issue by Riin** [libavg/libavg#719]
Hey there,

currently i give [gesture recognizer](www.libavg.de/reference/svn/gesture.html) a try. I like to detect taps, longtaps and doubletaps. Therefore I register a Recognizer for each event and give it a callback like below.

First question: The callbacks occure, but get no event parameter. How can i get the event and its postion without a given event?

Second question: I extracted the event from the contacts list (kinda hacky) and this is working for longtap, but not for tap or doubletap. There must be a better way to do this?

Third question: I let every callback print its name and event trigger multiple times like: 
* a doupletap causes two taps and one doubletap callback. 
* a lontap causes first a  longtap and then a tap callback

Is there something i can do to prevent recognizers from doing this?

Thank you

```
from libavg import avg
from libavg import app
from libavg import gesture

class ExampleDiv(app.MainDiv):

    def onInit(self):
        self._tap_recognizer = gesture.TapRecognizer(node=self, detectedHandler=self.__on_tap)
        self._longtap_recognizer = gesture.HoldRecognizer(node=self, detectedHandler=self.__on_longtap)
        self._doubletap_recognizer = gesture.DoubletapRecognizer(node=self, detectedHandler=self.__on_doubletap)

    def __on_tap(self):
        event = ExampleDiv.extract_event(self._tap_recognizer)
        print "tap detected: %s" % ExampleDiv.event_to_string(event)

    def __on_longtap(self):
        event = ExampleDiv.extract_event(self._longtap_recognizer)
        print "longtap detected: %s" % ExampleDiv.event_to_string(event)

    def __on_doubletap(self):
        event = ExampleDiv.extract_event(self._doubletap_recognizer)
        print "doubletap detected: %s" % ExampleDiv.event_to_string(event)

    @staticmethod
    def extract_event(recognizer):
        event = None
        if len(recognizer.contacts) > 0:
            con = recognizer.contacts[0]
            if len(con.events) > 0:
                event = con.events[0]
        return event

    @staticmethod
    def event_to_string(event):
        if event:
            return "event at %d,%d" % (event.x, event.y)
        return "None"

if __name__ == '__main__':
    mainDiv = ExampleDiv()
    app = app.App()
    app.run(mainDiv, app_resolution='800x600')
```

**Comment by uzadow** [comment]
Could you do us a favor and re-submit this using the forums? This isn't an issue with libavg, it's a question about using libavg.
