### ISSUE TITLE
Problem with glyph values from WordsNode

### ISSUE THREAD

**Issue by DevNils** [libavg/libavg#720]
Hello Folks,

while using the WordsNode I discovered a small bug.
I made use of getGlyphPos, getGlyphSize and getLineExtents. The problem is that those methods deliver the values of the last WordsNode you made changes to and not of the current WordsNode.
The appended example visualize the problem.

I discovered the problem on:
Linux gigasmart 3.19.0-39-generic #44~14.04.1-Ubuntu SMP Wed Dec 2 10:00:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Which uses pango 1.36.03. You won't find the problem on a Mac. It uses an older pango version (1.24.04)

I appended a patch that could solve the problem. I guess the font description needs to be set before you query the glyph values. If you like I could open a change request.

Thank you

Nils

Example:

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    
    
    from libavg import app, avg
    from libavg.app import MainDiv
    
    
    class MyMainDiv(MainDiv):
        def __init__(self, **kargs):
            super(MainDiv, self).__init__(**kargs)
    
            text = 'Lorem Ipsum Dolor'
    
            wordsNodeS = avg.WordsNode(
                parent=self,
                pos=(50, 50),
                width=500,
                text=text
            )
    
            wordsNodeL = avg.WordsNode(
                parent=self,
                pos=(50, 200),
                width=500,
                text=text,
                fontsize=50
            )
    
            self._visualize(wordsNodeS)
    
        def _visualize(self, wordsNode):
            for i, c in enumerate(wordsNode.text):
                gPos = wordsNode.getGlyphPos(i)
                gSize = wordsNode.getGlyphSize(i)
    
                avg.RectNode(
                    parent=self,
                    opacity=0,
                    fillopacity=0.2,
                    fillcolor='FF0000' if i % 2 else '00FF00',
                    pos=gPos+wordsNode.pos,
                    size=gSize
                )
    
                lSize = wordsNode.getLineExtents(0)
                avg.RectNode(
                    parent=self,
                    color='FF0000',
                    pos=wordsNode.pos,
                    size=lSize
                )
    
    
    if __name__ == '__main__':
        app.App().run(MyMainDiv())

Patch:

    diff --git src/player/WordsNode.cpp src/player/WordsNode.cpp
    index b7be8f6..3f33ac8 100644
    --- src/player/WordsNode.cpp
    +++ src/player/WordsNode.cpp
    @@ -742,6 +742,9 @@ PangoRectangle WordsNode::getGlyphRect(int i)
         PangoRectangle rect;

         if (m_pLayout) {
    +        TextEngine& engine = TextEngine::get(m_FontStyle.getHint());
    +        PangoContext* pContext = engine.getPangoContext();
    +        pango_context_set_font_description(pContext, m_pFontDescription);
             pango_layout_index_to_pos(m_pLayout, byteOffset, &rect);
         } else {
             rect.x = 0;

**Comment by uzadow** [comment]
Nice bugreport & nice fix :-).

**Comment by DevNils** [comment]
Hey Uli,

I am sorry but I was a little bit to fast.
I found other methods where a font descriptor update is necessary.
It is important for getNumLines, getCharIndexFromPos and getLineExtents.
Please check the patch:

	diff --git src/player/WordsNode.cpp src/player/WordsNode.cpp
	index c4278c3..8ba68c3 100644
	--- src/player/WordsNode.cpp
	+++ src/player/WordsNode.cpp
	@@ -404,9 +404,20 @@ glm::vec2 WordsNode::getGlyphSize(int i)
	     return glm::vec2(float(rect.width)/PANGO_SCALE, float(rect.height)/PANGO_SCALE);
	 }
	 
	+void setFontDescription(FontStyle fontStyle, PangoFontDescription *fontDescriptor)
	+{
	+    TextEngine& engine = TextEngine::get(fontStyle.getHint());
	+    PangoContext* pContext = engine.getPangoContext();
	+    pango_context_set_font_description(pContext, fontDescriptor);
	+}
	+
	 int WordsNode::getNumLines()
	 {
	     if(m_sText.length() != 0) {
	+        // For some pango versions (at least 1.36.03), we need to make sure that the
	+        // font description is set, otherwise the layout uses the font description of
	+        // the wrong font. (See bug #720).
	+        setFontDescription(m_FontStyle, m_pFontDescription);
		 return pango_layout_get_line_count(m_pLayout);
	     }
	     return 0;
	@@ -416,6 +427,10 @@ PyObject* WordsNode::getCharIndexFromPos(glm::vec2 p)
	 {
	     int index;
	     int trailing;
	+    // For some pango versions (at least 1.36.03), we need to make sure that the
	+    // font description is set, otherwise the layout uses the font description of
	+    // the wrong font. (See bug #720).
	+    setFontDescription(m_FontStyle, m_pFontDescription);
	     gboolean bXyToIndex = pango_layout_xy_to_index(m_pLayout,
		         int(p.x*PANGO_SCALE), int(p.y*PANGO_SCALE), &index, &trailing);
	     if (bXyToIndex) {
	@@ -439,6 +454,10 @@ glm::vec2 WordsNode::getLineExtents(int line)
	     }
	     PangoRectangle logical_rect;
	     PangoRectangle ink_rect;
	+    // For some pango versions (at least 1.36.03), we need to make sure that the
	+    // font description is set, otherwise the layout uses the font description of
	+    // the wrong font. (See bug #720).
	+    setFontDescription(m_FontStyle, m_pFontDescription);
	     PangoLayoutLine *layoutLine = pango_layout_get_line_readonly(m_pLayout, line);
	     pango_layout_line_get_pixel_extents(layoutLine, &ink_rect, &logical_rect);
	     return glm::vec2(float(logical_rect.width), float(logical_rect.height));
	@@ -745,9 +764,7 @@ PangoRectangle WordsNode::getGlyphRect(int i)
		 // For some pango versions (at least 1.36.03), we need to make sure that the
		 // font description is set, otherwise the layout uses the font description of
		 // the wrong font. (See bug #720).
	-        TextEngine& engine = TextEngine::get(m_FontStyle.getHint());
	-        PangoContext* pContext = engine.getPangoContext();
	-        pango_context_set_font_description(pContext, m_pFontDescription);
	+        setFontDescription(m_FontStyle, m_pFontDescription);
		 pango_layout_index_to_pos(m_pLayout, byteOffset, &rect);
	     } else {
		 rect.x = 0;

**Comment by uzadow** [comment]
No problem.

The new patch looks good, except - I'd move the duplicated comments to setFontDescription. Also, a branch and pull request would probably be a good thing now so we can see what the build server sais.

**Comment by DevNils** [comment]
Thanks. Ok. I'll do this.

**Comment by uzadow** [comment]
Thanks! Merged.
