### ISSUE TITLE
Parallel animation doesn't work on libavg

### ISSUE THREAD

**Issue by lgmventura** [libavg/libavg#735]
The parallel animation example shown in https://www.libavg.de/site/projects/libavg/wiki/Animation does not work. It simply throws "RuntimeError: Animated attributes must be either numbers or Point2D". There are several other examples with errors there.

**Comment by scotty007** [comment]
Which version of libavg are you using? Color animation support has been added in May 2015 and works with the current master.

**Comment by uzadow** [comment]
Thanks, scotty. I've updated the wiki page accordingly.

@lgmventura: I'm closing the bug. If this wasn't the reason, feel free to re-open!

**Comment by lgmventura** [comment]
I'm using the python-libavg 1.8.0-1. I thought it was the most recent one... I'll try finding the newest.
I've another issue... Should I open another topic?

Date: Mon, 18 Jan 2016 09:24:59 -0800

**Comment by uzadow** [comment]
Yeah, different issues should be dealt with in different topics. Also, if it's not a libavg bug, but a question of how to use libavg, please use the forums at https://www.libavg.de/site/projects/libavg/boards.

Note that scotty isn't talking about a newer release. This is a feature you'll only get if you compile libavg from current git master.

**Comment by lgmventura** [comment]
Thank you very much! I'll try doing this soon...
Best regards!
Luiz Ventura

Date: Mon, 18 Jan 2016 10:48:57 -0800
