### ISSUE TITLE
Error when calling indexOf(node)

### ISSUE THREAD

**Issue by MichaelBarz** [libavg/libavg#755]
Hi, I have a problem using the 'indexOf' function. I use Windows 8.1 with the recent release 1.8.

The class CustomNode inherits from avg.DivNode and is responsible to show and hide many images with labels. An image and a label are grouped by another class SubNode(avg.DivNode). I create and add the nodes as follows:

```
# from within CustomNode I call (triggered by setOnFrameHandler):
node = SubNode(start_time, bmp, label, parent=self)
node_list.append(node)
```

In addition I check if any node needs to be removed. I compare the start_time attribute of every node with the current time. Eventually I remove nodes on a regular basis:

```
for node in node_list:
  i = self.indexOf(node)
  self.removeChild(i)
```

The problem appearch sporadically when calling self.indexOf(node). The error claims that there is no such node. However, printing the number of children yields 1 (instead of 20-30) exactly to the time when the error ocurrs. If guess that the incorrect number of children and the error are correlated.

The exact error message is:
```
... line 71, in _update_nodes
i = self.indexOf(event)
RuntimeError: indexOf: node '' is not a child of node ''
```

Did someone face the same problem?
Or do you have an idea how to overcome the error?

Thanks in advance!

Best,
Michael

**Comment by uzadow** [comment]
I don't think the error is in the code you've described. DivNode.indexOf almost certainly works, since it's been unchanged for several years (i.e. this isn't a bug in libavg), so the error message is correct: You're trying to remove a node that isn't a child. How that is happening is not visible from your issue report.

**Comment by MichaelBarz** [comment]
Hi, thanks for the fast response. As it was not clear here is another code example:

```
class CustomNode(avg.DivNode):

node_list = []

def onFrame(self):
  for node in node_list:
    if check_time(node):
      self.removeChild(self.indexOf(node))

  node_list.append(new_sub_node(time()))
```

There is no error with a low amount of nodes. However, with a high amount of nodes and fast changes  the error ocurrs.

A wierd workaround such as `if self.getNumChildren() <= 1: continue` helps, but when further increasing the number of nodes even this does not work anymore.

I debugged my code and the number of children was 24, 1 (continued), 24. Something went wrong...

**Comment by uzadow** [comment]
Sorry, same issue: The code you're giving doesn't show the error. If you believe it is a libavg bug, please create a small sample that reproduces the error.

**Comment by MichaelBarz** [comment]
Ok, I'll try by tomorrow.
________________________________
