### ISSUE TITLE
Wrong documentation for libavg.avg.Node.unlink

### ISSUE THREAD

**Issue by satkowski** [libavg/libavg#773]
The documentation for the unlink method in libavg.avg.Node is wrong. The documentations says that there is one parameter: **kill = False**. I tried it this way but my programm stopped with an error.
The correct parameter should be: **bKill** like the error of the programm says.

**Comment by uzadow** [comment]
The documentation is correct. The parameter is a positional parameter, not a named parameter, so the function should just be called using `node.unlink(False)`.
