### ISSUE TITLE
widget.Button don't work porperly

### ISSUE THREAD

**Issue by satkowski** [libavg/libavg#779]
I've created a button with two seperated nodes for the down and up state. I also subscribed for all three event types a method.
The button never recognizes the input and so it never changes its own look or never triggers the subscribed methods.

Here is a smale example:

    from libavg import app, avg
    from libavg.widget.button import Button

    class TestDiv(app.MainDiv):

        def onInit(self):

            self.__rect_up = avg.RectNode(
                pos=(200, 200),
                size=(100, 100),
                fillcolor="00008b",
                fillopacity=1
            )

            self.__rect_down = avg.RectNode(
                pos=(200, 200),
                size=(100, 100),
                fillcolor="8b0000",
                fillopacity=1
            )

            self.__button = Button(
                upNode=self.__rect_up,
                downNode=self.__rect_down,
                parent=self,
            )
            self.__button.enabled = True
            self.__button.subscribe(self.__button.CLICKED, self.__on_button_clicked)
            self.__button.subscribe(self.__button.PRESSED, self.__on_button_pressed)
            self.__button.subscribe(self.__button.RELEASED, self.__on_button_released)

        def __on_button_clicked(self):
            print "Clicked"

        def __on_button_pressed(self):
            print "Pressed"

        def __on_button_released(self):
            print "Released"

    if __name__ == '__main__':
        app.App().run(TestDiv(), app_resolution="800,600")

**Comment by uzadow** [comment]
The issue is that the button is at position (0,0), but the rectangles are at (200,200). You need to set the position of self.__button, not of the rectangles.
