### ISSUE TITLE
Unexpected KEY_DOWN event immediately after KEY_UP on some keys

### ISSUE THREAD

**Issue by prosenkranz** [libavg/libavg#783]
Steps to reproduce:
1. Get the simple test script: https://gist.github.com/prosenkranz/3245c0982bd9ae3c3d898f51da21fa4b
2. Run script and repeatedly press the down-arrow for a few seconds then release it

The text should always stop moving down, when releasing the key.

**Sometimes** the text does not stop moving. Pay attention to the console output: there is a single `Key Down` event triggered immediately after the `Key Up` event, although no key was pressed.

I could not reproduce this issue with all keys.
Keys tested and failed: `Up`, `Down`, `Left`, `Right`, `Return`, `Insert`, `Delete`, `Backspace`, `F1`
Keys tested and worked as intended: `I`, `O`, `D`, `R`, `1`, `Space`

Tested with: libavg on the tabletop + two different machines running Windows 10 and libavg at 53aea51 + Arch linux

Edit:
The issue can also be reproduced in the firebirds demo (press Left or Right key for a while, then release it. Sometimes the aircraft will not stop moving)

**Comment by uzadow** [comment]
Thanks!
