### ISSUE TITLE
Repo description doesn't help with finding libavg

### ISSUE THREAD

**Issue by 0joshuaolson1** [libavg/libavg#791]

**Comment by uzadow** [comment]
Which repo description do you mean? On https://github.com/libavg/libavg, the main libavg website is linked twice: At the top under "Code" and in the text at the bottom.

Closing for now, feel free to reopen if this is not what you meant.

**Comment by 0joshuaolson1** [comment]
I don't mean the website, but the repo itself. A GitHub search for gui/window [language:]python wouldn't point anyone here.

**Comment by 0joshuaolson1** [comment]
Only you have the ability to reopen issues.
