### ISSUE TITLE
Build failed on OS X 10.11 with Xcode 8 (libxml2 error)

### ISSUE THREAD

**Issue by derric** [libavg/libavg#799]
Today, I failed to build the latest dev (master branch) of libavg on my iMac.

**Why?**
It is not really a libavg problem, more an specific platform issue. It seems that there is a problem with libxml2 on Xcode 8 and OS X 10.11 (El Capitan). See https://github.com/r-lib/xml2/issues/127 for details. My current configuration uses OS X El Capitan 10.11.6 and Xcode 8.2.1.

**How to fix it?**
There is a workaround for libavg users developing on a Mac. See https://stat.ethz.ch/pipermail/r-sig-mac/2016-September/012046.html:
> I had found a workaround for Xcode 8 on El Capitan: copy 
> /usr/bin/xml2-config to somewhere earlier on your path (~/bin in my 
> case) and edit line 3 from
>
> prefix=$(xcrun -show-sdk-path)/usr
> to
> prefix=/usr

This worked for me - so I am happy know. However, it might be useful for others as well.

**Comment by scotty007** [comment]
Outdated. The `macdependencies.*.tar.bz` based build has been dropped, dependencies provided by the system (e.g. via homebrew) are used now.
