### ISSUE TITLE
Inconsistency with radius in CircleNodes

### ISSUE THREAD

**Issue by satkowski** [libavg/libavg#801]
There exists an inconsistency with the radius of the CircleNodes. It's possible to create a CircleNode with a radius of 0 but not to set at any time the radius to 0. If this happens the following error occurs: `libavg.avg.Exception: Circle radius must be a positive number.`

Here is a small example of this problem:
```python
from libavg import avg, app


class TestClass(app.MainDiv):
    def onInit(self):
        # This will work, and no cirlce is visible at all.
        circle = avg.CircleNode(
            parent=self,
            pos=(400, 300),
            r=0,
            color="fff",
            fillcolor="fff",
            fillopacity=1
        )
        # If this line is executed, the error occures.
        circle.r = 0


if __name__ == '__main__':
    lib_app = app.App()
    lib_app.run(TestClass(), app_resolution='800x600')
```

Either both, the creation and the setting of the radius to 0, should throw this exception or both should work. I would like to see the second option to be implemented due to the possibility to create a circle with a radius of 0. This circle works like I would except it and will not be shown at all.

**Comment by uzadow** [comment]
Fixed with bbe3460.

Also fixed crash if r<0 on construction.
